<?php

namespace BeUbi\JobeetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
  public function getWithJobs()
  {
      $query = $this->createQueryBuilder('c')->select('c')
                                             ->leftJoin('c.jobs', 'j')
                                             ->where('j.expires_at > :date')
                                             ->andWhere('j.is_activated = :activated')
                                             ->setParameter('date', date('Y-m-d H:i:s', time()))
                                             ->setParameter('activated', 1)
                                             ->getQuery()->useResultCache(true, 90000, 'teste');

    return $query->getResult();
  }
}
